on: [push]

jobs:
  help_test:
    runs-on: ubuntu-latest
    name: Help Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SQLx action step
        uses: ./
        id: sqlx
        with:
          args: "--help"
